export type Hotel = {
  slug:string; name:string; destination:string; experience:string; description:string; room:string;
  image:string; address:string; phone?:string; tags:string[];
};

export const CENTRAL_PHONE = '+94752200202';
export const BOOKING_URL = 'https://lavendishleisure.com/booking/';

export const hotels: Hotel[] = [
  {slug:'grand-tamarind-lake',name:'Grand Tamarind Lake',destination:'Kataragama',experience:'Lake · Pilgrimage · Wildlife',description:'A peaceful Kataragama stay overlooking Detagamuwa Lake, close to the sacred city and within reach of Yala wildlife experiences.',room:'Deluxe rooms and spacious suites with lake, garden or pool outlooks.',image:'https://lavendishleisure.com/wp-content/uploads/2025/06/DSC03405-HDR-1-scaled-700x467.jpg',address:'Kandasuridugama Raja Mawatha, Kataragama',phone:'+94753556039',tags:['Family','Lake','Sacred journey']},
  {slug:'okrin-kataragama',name:'Lavendish Okrin',destination:'Kataragama',experience:'Pilgrimage · Nature · Family',description:'A relaxed Kataragama hotel beside Detagamuwa Tank and close to Wedihiti Kanda, offering a convenient base for families and religious travellers.',room:'Deluxe rooms and larger suite-style accommodation.',image:'https://lavendishleisure.com/wp-content/uploads/2025/06/IMG_0184-scaled-700x467.jpg',address:'No. 10, Detagamuwa, Kataragama',phone:'+94753556044',tags:['Family','Nature','Kataragama']},
  {slug:'tamarind-lifestyle',name:'Lavendish Tamarind Lifestyle',destination:'Kataragama',experience:'Family · Pilgrimage · Pool',description:'Comfortable accommodation in Kataragama with convenient access to the temple area and Yala, surrounded by tropical greenery and a restful atmosphere.',room:'Deluxe and family-friendly room options with pool or garden views.',image:'https://lavendishleisure.com/wp-content/uploads/2025/06/621180597-700x467.jpg',address:'Raja Mawatha, Kataragama',phone:'+94753556130',tags:['Pool','Family','Yala']},
  {slug:'miridiya-lake-resort',name:'Miridiya Lake Resort',destination:'Anuradhapura',experience:'Heritage · Lake · Family',description:'A refurbished lakeside resort in historic Anuradhapura, combining easy access to the ancient city with a calm setting by Nuwara Wewa.',room:'Deluxe rooms and suites with garden or lake outlooks.',image:'https://lavendishleisure.com/wp-content/uploads/2025/06/49709742-700x467.jpg',address:'Wasaladantha Mawatha, Anuradhapura',phone:'+94752555921',tags:['Heritage','Lake','Family']},
  {slug:'lavendish-lake-giritale',name:'Lavendish Lake Giritale',destination:'Giritale',experience:'Lake · Heritage · Relaxation',description:'A tranquil escape by Giritale Lake with scenic sunsets, warm hospitality and convenient access to the cultural triangle.',room:'Deluxe and superior deluxe rooms designed for a relaxed lakeside stay.',image:'https://lavendishleisure.com/wp-content/uploads/2025/06/199397865-700x467.jpg',address:'Giritale, Polonnaruwa',tags:['Lake','Relaxation','Heritage']},
  {slug:'beach-resort-unawatuna',name:'Lavendish Beach Resort',destination:'Unawatuna',experience:'Beach · Family · Couples',description:'A coastal stay in Unawatuna near the beach, combining tropical surroundings, comfortable rooms and easy access to Galle and the south coast.',room:'Deluxe and superior deluxe rooms with garden or coastal outlooks.',image:'https://lavendishleisure.com/wp-content/uploads/2025/06/Copy-of-Copy-of-DSC00985-2-HDR-scaled-700x467.jpg',address:'Ganehena, Unawatuna',phone:'+94912283201',tags:['Beach','Couples','Family']},
  {slug:'wild-safari-wasgamuwa',name:'Lavendish Wild Safari',destination:'Wasgamuwa',experience:'Wildlife · Nature · Family',description:'A nature-focused hotel set amid Wasgamuwa scenery, with access to wildlife experiences, open landscapes and views towards the Knuckles range.',room:'Deluxe rooms and suite-style options with garden, pool or landscape views.',image:'https://lavendishleisure.com/wp-content/uploads/2025/06/h-1-scaled-700x467.jpg',address:'Wasgamuwa',tags:['Wildlife','Safari','Nature']},
  {slug:'wild-wilpattu',name:'Lavendish Wild Wilpattu',destination:'Nochchiyagama',experience:'Wildlife · Nature · Safari',description:'A quiet nature retreat near Wilpattu National Park, surrounded by paddy fields and suited to travellers planning safari adventures.',room:'Standard and deluxe rooms with practical comforts for nature-focused stays.',image:'https://lavendishleisure.com/wp-content/uploads/2025/06/WhatsApp-Image-2024-09-09-at-12.39.37-1-700x467.jpeg',address:'Puttalam Road, Sinharagama, Nochchiyagama',phone:'+94252056001',tags:['Wilpattu','Safari','Nature']},
  {slug:'hills-kandy',name:'Lavendish Hills Kandy',destination:'Kandy',experience:'Hills · Heritage · City',description:'A Kandy city stay with convenient access to cultural attractions and hill-country experiences while offering a calmer place to unwind.',room:'Deluxe rooms with city or mountain outlooks and modern essentials.',image:'https://lavendishleisure.com/wp-content/uploads/2026/03/DSC00092-1-scaled-700x467.jpg',address:'No. 12, Old Matale Road, Kandy',phone:'+94753581186',tags:['Kandy','Hills','Heritage']},
  {slug:'country-resort-dambulla',name:'Lavendish Country Resort',destination:'Dambulla',experience:'Heritage · Family · Nature',description:'A relaxed Dambulla base with a pool, restaurant and easy access to the cave temple, Sigiriya and the cultural triangle.',room:'Comfortable standard rooms in a peaceful green setting.',image:'https://lavendishleisure.com/wp-content/uploads/2025/06/Room-3-700x467.jpg',address:'01 Mile Post, Kandalama Road, Dambulla',phone:'+94753556071',tags:['Dambulla','Sigiriya','Family']}
];

export const hotelBySlug = (slug:string) => hotels.find(h=>h.slug===slug);
export const waLink = (name='Lavendish Leisure') => `https://wa.me/${CENTRAL_PHONE.replace('+','')}?text=${encodeURIComponent(`Hi, I would like to check rates and availability for ${name}.`)}`;
