'use client';
import {useEffect,useState} from 'react';
import {CalendarIcon,PhoneIcon,WhatsAppIcon,MapIcon} from '@/components/Icons';
import {CENTRAL_PHONE,waLink} from '@/lib/hotels';
export default function MyStay(){const [ref,setRef]=useState('');const [saved,setSaved]=useState('');useEffect(()=>setSaved(localStorage.getItem('lavendish:bookingRef')||''),[]);const save=()=>{if(ref.trim()){localStorage.setItem('lavendish:bookingRef',ref.trim());setSaved(ref.trim())}};return <>
 <section className="pageTop gradientTop"><p className="eyebrow">YOUR TRIP</p><h1>My Stay</h1><p>Keep the essentials in one calm place.</p></section>
 {saved?<section className="stayCard"><div className="stayIcon"><CalendarIcon/></div><p className="eyebrow">BOOKING REFERENCE</p><h2>{saved}</h2><p>Your reference is saved on this device. Full booking sync can be connected to the booking engine in the next phase.</p><div className="stayQuick"><a href={`tel:${CENTRAL_PHONE}`}><PhoneIcon/>Call</a><a href={waLink(`booking ${saved}`)}><WhatsAppIcon/>WhatsApp</a><a href="https://www.google.com/maps" target="_blank"><MapIcon/>Directions</a></div><button className="textButton" onClick={()=>{localStorage.removeItem('lavendish:bookingRef');setSaved('')}}>Remove reference</button></section>:<section className="emptyStay"><div className="bigIcon"><CalendarIcon/></div><h2>Add your stay</h2><p>Enter your Lavendish booking reference for quicker access during your trip.</p><div className="bookingInput"><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="Booking reference"/><button onClick={save}>Save</button></div><a href={waLink('my upcoming stay')}>Need help? WhatsApp reservations</a></section>}
 <section className="tripBenefits"><div><strong>Before arrival</strong><span>Contact · directions · hotel info</span></div><div><strong>During your stay</strong><span>Quick assistance in one touch</span></div><div><strong>After your stay</strong><span>Return offers & member benefits</span></div></section>
 </>}
